### ISSUE TITLE
Potential dependency conflicts between bcdata and click

### ISSUE THREAD

**Issue by NeolithEra** [smnorris/bcdata#68] opened 2019-12-28 13:54 UTC
Hi, as shown in the following full dependency graph of  **_bcdata_**, **_bcdata_** requires **_click  *_** ， while the installed version of **_cligj_**(0.5.0) requires _**click <8,>=4.0**_.

According to Pip's _“first found wins”_ installation strategy, _**click 7.0**_ is the actually installed version.  

Although the first found package version _**click 7.0**_ just satisfies the later dependency constraint （_**click <8,>=4.0**_), it will lead to a build failure once developers release a newer version of click.

### Dependency tree--------
```
bcdata - 0.3.5
| +- click(install version:7.0 version range:*)
| +- cligj(install version:0.5.0 version range:*)
| | +- click(install version:7.0 version range:<8,>=4.0)
| +- owslib(install version:0.19.0 version range:*)
| | +- pyproj(install version:2.4.1 version range:*)
| | +- python-dateutil(install version:2.8.1 version range:>=1.5)
| | +- pytz(install version:2019.3 version range:*)
| | +- requests(install version:2.22.0 version range:>=1.0)
| | | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- pgdata(install version:0.0.12 version range:*)
| | +- alembic(install version:1.3.1 version range:*)
| | | +- mako(install version:1.1.0 version range:*)
| | | | +- markupsafe(install version:1.1.1 version range:>=0.9.2)
| | | +- python-dateutil(install version:2.8.1 version range:*)
| | | +- python-editor(install version:1.0.4 version range:>=0.3)
| | | +- sqlalchemy(install version:1.3.10 version range:>=1.1.0)
| | +- geoalchemy2(install version:0.6.3 version range:*)
| | | +- sqlalchemy(install version:1.3.10 version range:>=0.8)
| | +- psycopg2-binary(install version:2.8.4 version range:*)
| | +- sqlalchemy(install version:1.3.10 version range:*)
| | +- sqlalchemy-utils(install version:0.35.0 version range:*)
| | | +- six(install version:1.13.0 version range:*)
| | | +- sqlalchemy(install version:1.3.10 version range:>=1.0)
| +- rasterio(install version:1.1.1 version range:*)
| +- requests(install version:2.22.0 version range:*)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment] 2019-12-28 13:55
### Suggested Solution

1.	Fix your direct dependencies to be **_click <8_**.
2.	Ask your upstream project **_cligj_** to losse the version range of **_click_** to be **_>=4.0_**.

@smnorris Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by smnorris** [comment] 2020-01-06 22:10
#1 please, a PR is welcome. I'm not sure exactly why cligj specifies click < 8 but I'm happy to defer to the choice made by maintainers of cligj.

**Comment by smnorris** [comment] 2020-01-06 22:31
Note that `setup.py` already specifies the versions allowed, I thought pip would use this.
https://github.com/smnorris/bcdata/blob/master/setup.py#L24

**Comment by smnorris** [comment] 2020-02-28 03:28
duplicate of #64

**Closed by smnorris** 2020-02-28 03:28 UTC
